spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
      - id: welcome-api
        uri: lb://welcome-api
        predicates:
        - Path=/welcome
      - id: greet-api
        uri: lb://greet-api
        predicates:
        - Path=/greet


server:
  port: 3333
