spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JonnagaddalaVaishnavi/configuration_properties

server:
  port: 4044
